#! /usr/bin/expect -f

spawn ssh -g -L 6666:localhost:$env(PORT) -N $env(USER)@$env(HOST) -p $env(SSH_PORT) \
        -o NumberOfPasswordPrompts=2 \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o ServerAliveInterval=$env(ALIVE_INTERVAL) \
        -o ServerAliveCountMax=$env(ALIVE_COUNT_MAX)
expect "assword:"
send -- "$env(PASSWORD)\r"
expect {
  "assword:" {
    sleep 5
    exit
  }
}
wait

