name: laravel-dev

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build laravel-dev
      run: |
        image="docker.pkg.github.com/$GITHUB_REPOSITORY/laravel-dev"
        dockerfile='laravel-dev/Dockerfile'
        docker login -u GITHUB_ACTIONS -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        for base_image in `cat "$dockerfile" | grep FROM | awk '{ print $2 }`
        do
          docker pull "$base_image"
        done
        docker pull "$image"
        docker build laravel-dev --file "$dockerfile" --tag "$image" --cache-from "$image"
        docker push "$image"
