name: laravel-dev

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build laravel-dev
      run: |
        image="docker.pkg.github.com/$GITHUB_REPOSITORY/laravel-dev"
        docker login -u yanzhen -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker pull "$image"
        docker build laravel-dev --file laravel-dev/Dockerfile --tag "$image"
        docker push "$image"
