name: laravel-dev

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/laravel-dev
      DOCKERFILE: laravel-dev/Dockerfile

    steps:
    - uses: actions/checkout@v2
      
    - name: Authenticate
      run: docker login -u GITHUB_ACTIONS -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

    - name: Pull Dependencies
      run: for base_image in `cat "$DOCKERFILE" | grep FROM | awk '{ print $2 }'` ; do docker pull "$base_image" ; done
      
    - name: Pull Last Built Image
      run: docker pull "$IMAGE"
      
    - name: Build Image
      run: docker build laravel-dev --file "$DOCKERFILE" --tag "$IMAGE" --cache-from "$IMAGE"
      
    - name: Push Image
      run: docker push "$IMAGE"
